[dependencies]
std = "lukadev-0/std@1.0.2"

[package]
authors = ["LukaDev <luka@lukadev.me> (https://lukadev.me/)"]
description = "Spawn threads using a thread pool"
license = "MIT"
name = "lukadev-0/threadpool"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.0.2"
