[dependencies]

[package]
authors = ["LukaDev <luka@lukadev.me> (https://lukadev.me/)"]
description = "Runtime agnostic access to standard libraries"
license = "MIT"
name = "lukadev-0/std"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.0.2"
