[dependencies]

[package]
authors = ["LukaDev <luka@lukadev.me> (https://lukadev.me/)"]
description = "Option<T> type in Luau"
license = "MIT"
name = "lukadev-0/option"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.2.1"
