[dependencies]
option = "lukadev-0/option@1.2.1"
std = "lukadev-0/std@1.0.2"
threadpool = "lukadev-0/threadpool@1.0.2"

[package]
authors = ["LukaDev <luka@lukadev.me> (https://lukadev.me/)"]
description = "Future<T> type in Luau"
license = "MIT"
name = "lukadev-0/future"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.0.2"
